#ifndef UI_SCREEN_CANVAS_MENU_HPP
#define UI_SCREEN_CANVAS_MENU_HPP

#include "ui_core.hpp"

#define SCREEN_CANVAS_UI_ACTION_BAR_DIST_FROM_TOP_PX 5
#define SCREEN_CANVAS_UI_ACTION_BAR_HEIGHT 50
#define SCREEN_CANVAS_UI_ACTION_BAR_ITEM_WIDTH_PX 110
#define SCREEN_CANVAS_UI_ACTION_BAR_ITEM_HEIGHT_PX 25
#define SCREEN_CANVAS_UI_ACTION_BUTTON_COUNT 4
#define SCREEN_CANVAS_UI_ACTION_BUTTON_SPACING ((TFT_HOR_RES - (SCREEN_CANVAS_UI_ACTION_BUTTON_COUNT * SCREEN_CANVAS_UI_ACTION_BAR_ITEM_WIDTH_PX)) / (SCREEN_CANVAS_UI_ACTION_BUTTON_COUNT + 1))
#define SCREEN_CANVAS_UI_ACTION_BUTTON_X_POS(col) (SCREEN_CANVAS_UI_ACTION_BUTTON_SPACING + ((col) * (SCREEN_CANVAS_UI_ACTION_BAR_ITEM_WIDTH_PX + SCREEN_CANVAS_UI_ACTION_BUTTON_SPACING)))

#define SCREEN_CANVAS_UI_COLOR_BAR_DIST_FROM_BOTTOM_PX 5
#define SCREEN_CANVAS_UI_COLOR_BAR_ITEM_HEIGHT_PX 50
#define SCREEN_CANVAS_UI_COLOR_BAR_ITEM_WIDTH_PX 27
#define SCREEN_CANVAS_UI_COLOR_BUTTON_COUNT 16 // This should technically be static at 16 due to 4-bit color.
#define SCREEN_CANVAS_UI_COLOR_BUTTON_SPACING ((TFT_HOR_RES - (16 * SCREEN_CANVAS_UI_COLOR_BAR_ITEM_WIDTH_PX)) / 16)
#define SCREEN_CANVAS_UI_COLOR_BUTTON_X_POS(col) (SCREEN_CANVAS_UI_COLOR_BUTTON_SPACING + ((col) * (SCREEN_CANVAS_UI_COLOR_BAR_ITEM_WIDTH_PX + SCREEN_CANVAS_UI_COLOR_BUTTON_SPACING)))

#define CANVAS_DRAW_MENU_DROPDOWN_DIST_BETWEEN_ITEMS 5
#define TOOL_DROPDOWN_BUTTON_COUNT 6
#define SCREEN_CANVAS_MENU_TOOL_SETTINGS_BUTTON_COUNT 6
#define MENU_DROPDOWN_BUTTON_COUNT 5
#define SLOT_DROPDOWN_BUTTON_COUNT 7

void initUIForScreenCanvasMenu();
void handleTouchUIUpdateScreenCanvasMenu();
void drawScreenCanvasMenu();

#endif
