#!/usr/bin/env python3
"""Convert an image to src/lt_splash_data.cpp — an 8bpp (RGB332) boot splash
blob for the LT7680. The LT7680 canvas in 8bpp mode is RGB332 (RRRGGGBB), which
is exactly what display.cpp's _rgb565_to_clut8 produces, so the DMA'd splash
displays directly.

Usage:  python3 tools/png_to_fbox8.py <image>  [max_w max_h]
Requires Pillow:  pip install pillow
"""
import os, sys

def rgb332(r, g, b):
    return ((r >> 5) << 5) | ((g >> 5) << 2) | (b >> 6)

def main():
    if len(sys.argv) < 2:
        print(__doc__); sys.exit(1)
    try:
        from PIL import Image
    except ImportError:
        print("Pillow required: pip install pillow"); sys.exit(1)

    path = sys.argv[1]
    max_w = int(sys.argv[2]) if len(sys.argv) > 2 else 240
    max_h = int(sys.argv[3]) if len(sys.argv) > 3 else 240

    img = Image.open(path).convert("RGB")
    img.thumbnail((max_w, max_h))
    w, h = img.size
    data = [rgb332(*img.getpixel((x, y))) for y in range(h) for x in range(w)]

    here = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
    out = os.path.join(here, "src", "lt_splash_data.cpp")
    with open(out, "w") as f:
        f.write("// AUTO-GENERATED by tools/png_to_fbox8.py — do not edit by hand.\n")
        f.write(f"// Source: {os.path.basename(path)}  ({w}x{h}, 8bpp RGB332)\n")
        f.write('#include "lt_assets.hpp"\n\n')
        f.write(f"const uint16_t lt_splash_w = {w};\n")
        f.write(f"const uint16_t lt_splash_h = {h};\n")
        f.write("const uint8_t lt_splash_data[] = {\n")
        for i in range(0, len(data), 16):
            f.write("    " + ", ".join(f"0x{v:02X}" for v in data[i:i+16]) + ",\n")
        f.write("};\n")
    print(f"wrote {out} ({w}x{h}, {len(data)} bytes)")

if __name__ == "__main__":
    main()
